apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: anuja-cloud-run-ml-app
description: Pipeline for ML Sales Prediction App with Canary Rollout
serialPipeline:
  stages:
  - targetId: dev_anuja
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25,75]
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev_anuja
description: dev canary ml app Run Service
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1
  service: anuja-cloud-run-ml-app-pipeline
