# apiVersion: skaffold/v4beta7
# kind: Config
# manifests:
#   rawYaml:
#   - run.yaml
# deploy:
#   cloudrun: {}

apiVersion: skaffold/v4beta7
kind: Config
profiles:
  - name: dev
    manifests:
      rawYaml:
        - run.yaml
    deploy:
      cloudrun: {}
        # projectId: faa-gcp-training-14-kfa-0808
        # region: us-central1
        # serviceName: anuja-cloud-run-ml-app-pipeline
